---
- name: 'provision'
  hosts: all
  become: true

  tasks:

  - name: Install epel
    yum:
      name: epel-release
      state: present

  # Packer

  - name: Add hashicorp repo
    ansible.builtin.yum_repository:
      name: hashicorp
      description: Hashicorp Stable - $basearch
      file: hashicorp
      baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
      enabled: yes
      gpgcheck: yes
      gpgkey: https://rpm.releases.hashicorp.com/gpg
    register: hashicorp_repo

  - name: Update yum cache
    yum:
      update_cache: yes
    when: hashicorp_repo.changed

  - name: Install packer
    yum:
      name: packer
      state: present

  # KVM

  - name: install the 'virtualization-host' package group
    yum: 
      name: "@Virtualization Hypervisor" 
      state: present

  - name: Add users to libvirtd
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups: libvirt
      createhome: yes

  - name: start libvirtd service
    service: 
      name: libvirtd 
      state: started 
      enabled: yes

  - name: qemu-system-x86_64 symbolic link
    ansible.builtin.file:
      src: /usr/libexec/qemu-kvm
      dest: /usr/local/bin/qemu-system-x86_64
      state: link

  # Ansible

  - name: Install ansible
    yum:
      name: ansible
      state: present

  # Git

  - name: Install git
    yum:
      name: git
      state: present

  - name: git checkout
    ansible.builtin.git:
      repo: https://github.com/valengus/aws_ami.git
      dest: /aws_ami
      
  - name: Recursively change ownership of a directory /aws_ami
    ansible.builtin.file:
      path: /aws_ami
      state: directory
      recurse: yes
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"