---
- name: 'provision'
  hosts: all
  become: true

  tasks:

  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest

  - name: Install epel
    yum:
      name: epel-release
      state: present

  # Packer

  - name: Add hashicorp repo
    ansible.builtin.yum_repository:
      name: hashicorp
      description: Hashicorp Stable - $basearch
      file: hashicorp
      baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
      enabled: yes
      gpgcheck: yes
      gpgkey: https://rpm.releases.hashicorp.com/gpg
    register: hashicorp_repo

  - name: Update yum cache
    yum:
      update_cache: yes
    when: hashicorp_repo.changed

  - name: Install packer
    yum:
      name: packer
      state: present

  # KVM

  # - name: install the 'virtualization-host' package group
  #   yum: 
  #     name: "@Virtualization Hypervisor" 
  #     state: present

  # - name: Add user to libvirtd
  #   user:
  #     name: "{{ ansible_user }}"
  #     append: yes
  #     groups: libvirt
  #     createhome: yes

  # - name: start libvirtd service
  #   service: 
  #     name: libvirtd 
  #     state: started 
  #     enabled: yes

  # - name: qemu-system-x86_64 symbolic link
  #   ansible.builtin.file:
  #     src: /usr/libexec/qemu-kvm
  #     dest: /usr/local/bin/qemu-system-x86_64
  #     state: link

  # Virtualbox

  - name: Install additional software
    dnf:
      name:
        - kernel-uek-devel
        - gcc
        - make
        - perl
        - bzip2
        - dkms
      state: present

  - name: Install VirtualBox-6.1
    dnf:
      name: https://download.virtualbox.org/virtualbox/6.1.36/VirtualBox-6.1-6.1.36_152435_el8-1.x86_64.rpm
      disable_gpg_check: yes
      state: present

  - name: Add user to vboxusers
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups: vboxusers
      createhome: yes

  # Ansible

  - name: Install ansible
    yum:
      name: ansible
      state: present

  # Git

  - name: Install git
    yum:
      name: git
      state: present

  - name: git checkout
    ansible.builtin.git:
      repo: https://github.com/valengus/aws_ami.git
      dest: /aws_ami
      
  - name: Recursively change ownership of a directory /aws_ami
    ansible.builtin.file:
      path: /aws_ami
      state: directory
      recurse: yes
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"